"""increase product name allowed length

Revision ID: 25e2b563d085
Revises: d4f378be5df6
Create Date: 2020-11-12 09:54:56.304040

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "25e2b563d085"
down_revision = "d4f378be5df6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "product",
        "name",
        existing_type=sa.VARCHAR(length=63),
        type_=sa.String(length=127),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "product",
        "name",
        existing_type=sa.String(length=127),
        type_=sa.VARCHAR(length=63),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
