"""location names can have duplicates

Revision ID: 0d6f640db7fb
Revises: 0b24036dd206
Create Date: 2020-10-19 21:03:03.343621

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "0d6f640db7fb"
down_revision = "0b24036dd206"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("location_organization_id_name_key", "location", type_="unique")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "location_organization_id_name_key", "location", ["organization_id", "name"]
    )
    # ### end Alembic commands ###
