"""In products, every vendor should have a uniq vendor part number

Revision ID: 7a73ee113025
Revises: 6045a4ef8400
Create Date: 2020-10-22 20:50:42.486239

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "7a73ee113025"
down_revision = "6045a4ef8400"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        None,
        "product",
        ["organization_id", "preferred_vendor_id", "preferred_vendor_part_number"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "product", type_="unique")
    # ### end Alembic commands ###
