"""vendor erp_number is not globally unique

Revision ID: d1d940c531bb
Revises: 0e7d01f36cd4
Create Date: 2020-11-04 10:01:47.936229

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d1d940c531bb"
down_revision = "0e7d01f36cd4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("vendor_erp_number_key", "vendor", type_="unique")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("vendor_erp_number_key", "vendor", ["erp_number"])
    # ### end Alembic commands ###
