"""accept decimals in product qty

Revision ID: fb306e543dc6
Revises: 25e2b563d085
Create Date: 2020-11-18 08:46:19.549447

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "fb306e543dc6"
down_revision = "25e2b563d085"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "bin_family",
        "default_quantity",
        existing_type=sa.INTEGER(),
        type_=sa.Float(),
        existing_nullable=True,
    )
    op.alter_column(
        "bin_family", "location_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "bin_family", "product_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "organization", "name", existing_type=sa.VARCHAR(length=128), nullable=False
    )
    op.alter_column(
        "organization", "slug", existing_type=sa.VARCHAR(length=128), nullable=False
    )
    op.alter_column(
        "product", "name", existing_type=sa.VARCHAR(length=127), nullable=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "product", "name", existing_type=sa.VARCHAR(length=127), nullable=True
    )
    op.alter_column(
        "organization", "slug", existing_type=sa.VARCHAR(length=128), nullable=True
    )
    op.alter_column(
        "organization", "name", existing_type=sa.VARCHAR(length=128), nullable=True
    )
    op.alter_column(
        "bin_family", "product_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "bin_family", "location_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "bin_family",
        "default_quantity",
        existing_type=sa.Float(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
