"""add binfam id to move bin activity

Revision ID: 0b24036dd206
Revises: b7a978a2df9e
Create Date: 2020-10-16 17:14:32.424450

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0b24036dd206"
down_revision = "b7a978a2df9e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "activity_move_bin", sa.Column("bin_family_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        None, "activity_move_bin", "bin_family", ["bin_family_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "activity_move_bin", type_="foreignkey")
    op.drop_column("activity_move_bin", "bin_family_id")
    # ### end Alembic commands ###
