"""dump

Revision ID: 0e7d01f36cd4
Revises: afa228c07b83
Create Date: 2020-10-25 23:54:51.546237

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0e7d01f36cd4"
down_revision = "afa228c07b83"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("role", "name", existing_type=sa.VARCHAR(length=80), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("role", "name", existing_type=sa.VARCHAR(length=80), nullable=True)
    # ### end Alembic commands ###
