"""add move bin activity table

Revision ID: b7a978a2df9e
Revises: 0a2d3f8b2ecb
Create Date: 2020-10-16 16:38:08.793645

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b7a978a2df9e"
down_revision = "0a2d3f8b2ecb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activity_move_bin",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column("activity_id", sa.Integer(), nullable=True),
        sa.Column("prev_location_id", sa.Integer(), nullable=True),
        sa.Column("new_location_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["activity_id"],
            ["activity.id"],
        ),
        sa.ForeignKeyConstraint(
            ["new_location_id"],
            ["location.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
        ),
        sa.ForeignKeyConstraint(
            ["prev_location_id"],
            ["location.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "shopping_list", sa.Column("status", sa.String(length=63), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("shopping_list", "status")
    op.drop_table("activity_move_bin")
    # ### end Alembic commands ###
