"""increase product name & desc length

Revision ID: d4f378be5df6
Revises: d1d940c531bb
Create Date: 2020-11-04 17:00:43.941378

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d4f378be5df6"
down_revision = "d1d940c531bb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "product",
        "description",
        existing_type=sa.VARCHAR(length=128),
        type_=sa.String(length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "product",
        "name",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.String(length=63),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "product",
        "name",
        existing_type=sa.String(length=63),
        type_=sa.VARCHAR(length=50),
        existing_nullable=True,
    )
    op.alter_column(
        "product",
        "description",
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=128),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
