"""remove uniqs on vendor_part_number

Revision ID: 6045a4ef8400
Revises: 0d6f640db7fb
Create Date: 2020-10-20 23:12:28.295831

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "6045a4ef8400"
down_revision = "0d6f640db7fb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "product_organization_id_preferred_vendor_part_number_key",
        "product",
        type_="unique",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "product_organization_id_preferred_vendor_part_number_key",
        "product",
        ["organization_id", "preferred_vendor_part_number"],
    )
    # ### end Alembic commands ###
