"""make shopping list qty float

Revision ID: 83eb5aac5793
Revises: fb306e543dc6
Create Date: 2020-11-21 00:24:50.846798

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "83eb5aac5793"
down_revision = "fb306e543dc6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "shopping_list",
        "quantity",
        existing_type=sa.INTEGER(),
        type_=sa.Float(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "shopping_list",
        "quantity",
        existing_type=sa.Float(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
