"""use non native enum

Revision ID: f6f82d96f180
Revises: eabc0e6e61c9
Create Date: 2021-01-29 01:04:46.091789

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "f6f82d96f180"
down_revision = "eabc0e6e61c9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "license_plate", "location_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "license_plate", "product_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "license_plate",
        "quantity",
        existing_type=postgresql.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "license_plate",
        "quantity",
        existing_type=postgresql.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.alter_column(
        "license_plate", "product_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "license_plate", "location_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###
