"""remove remaining qty in license_plate

Revision ID: eabc0e6e61c9
Revises: f2d6512a2a56
Create Date: 2021-01-18 02:26:41.281685

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "eabc0e6e61c9"
down_revision = "f2d6512a2a56"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("license_plate", sa.Column("quantity", sa.Float(), nullable=True))
    op.drop_column("license_plate", "remaining_qty")
    op.drop_column("license_plate", "starting_qty")
    op.add_column(
        "license_plate_move", sa.Column("product_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(None, "license_plate_move", "product", ["product_id"], ["id"])
    op.drop_column("license_plate_move", "move_qty")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "license_plate_move",
        sa.Column(
            "move_qty",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_constraint(None, "license_plate_move", type_="foreignkey")
    op.drop_column("license_plate_move", "product_id")
    op.add_column(
        "license_plate",
        sa.Column(
            "starting_qty",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "license_plate",
        sa.Column(
            "remaining_qty",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("license_plate", "quantity")
    # ### end Alembic commands ###
