"""make activity_type nullable

Revision ID: 9b1937047211
Revises: 0a7b594b2f8a
Create Date: 2021-03-09 17:22:52.826441

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "9b1937047211"
down_revision = "0a7b594b2f8a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
