"""add redirect_url to pick

Revision ID: 487fb7b64f8b
Revises: c039038b2d27
Create Date: 2021-04-08 01:20:15.057810

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "487fb7b64f8b"
down_revision = "c039038b2d27"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "pick", sa.Column("redirect_url", sa.String(length=127), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pick", "redirect_url")
    # ### end Alembic commands ###
