"""add dims to location

Revision ID: 7cd38a3c1b0b
Revises: e6922e7fad6a
Create Date: 2021-12-24 23:01:30.229976

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7cd38a3c1b0b"
down_revision = "e6922e7fad6a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("location", sa.Column("depth", sa.Float(), nullable=True))
    op.add_column("location", sa.Column("height", sa.Float(), nullable=True))
    op.add_column("location", sa.Column("width", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("location", "width")
    op.drop_column("location", "height")
    op.drop_column("location", "depth")
    # ### end Alembic commands ###
