"""add external docid

Revision ID: e0c26421e23f
Revises: 284613612228
Create Date: 2021-03-26 03:25:18.341888

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e0c26421e23f"
down_revision = "284613612228"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "pick", sa.Column("external_docid", sa.CHAR(length=63), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pick", "external_docid")
    # ### end Alembic commands ###
