"""make user_id mandate for wms

Revision ID: ed9f7a3aa07b
Revises: e63a28c6f873
Create Date: 2021-01-29 02:09:19.272322

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ed9f7a3aa07b"
down_revision = "e63a28c6f873"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "license_plate_move", "user_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column("pickticket", "user_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("pickticket", "user_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column(
        "license_plate_move", "user_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###
