"""fix user status

Revision ID: 28226721d4aa
Revises: 4171f227a4c7
Create Date: 2021-02-25 08:02:25.909227

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "28226721d4aa"
down_revision = "4171f227a4c7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
