"""Add loggedin_user_id to activity

Revision ID: f504539b604c
Revises: d08fb64c6ed5
Create Date: 2021-05-07 02:02:16.240066

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f504539b604c"
down_revision = "d08fb64c6ed5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "activity", sa.Column("loggedin_user_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(None, "activity", "user", ["loggedin_user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "activity", type_="foreignkey")
    op.drop_column("activity", "loggedin_user_id")
    # ### end Alembic commands ###
