"""manual migration to fix accidents

Revision ID: 9794c4ea2f56
Revises: ed9f7a3aa07b
Create Date: 2021-01-29 02:24:56.405948

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9794c4ea2f56"
down_revision = "ed9f7a3aa07b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "pickticket_lineitem", "product_id", existing_type=sa.INTEGER(), nullable=False
    )

    op.add_column(
        "license_plate",
        sa.Column("parent_license_plate_id", sa.Integer(), nullable=True),
    )
    op.create_foreign_key(
        None,
        "license_plate",
        "license_plate",
        ["parent_license_plate_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "pickticket_lineitem", "product_id", existing_type=sa.INTEGER(), nullable=True
    )

    op.drop_constraint(None, "license_plate", type_="foreignkey")
    op.drop_column("license_plate", "parent_license_plate_id")
    # ### end Alembic commands ###
