"""rename active to status column in user table

Revision ID: 6513cf6599fc
Revises: 9794c4ea2f56
Create Date: 2021-02-09 23:57:38.558579

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6513cf6599fc"
down_revision = "9794c4ea2f56"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "status",
            sa.Enum(
                "UNCONFIRMED",
                "ACTIVE",
                "DELETED",
                name="userstatusenum",
                native_enum=False,
            ),
            nullable=True,
        ),
    )
    op.drop_column("user", "active")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "active",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("user", "status")
    # ### end Alembic commands ###
