"""fix docid datatypes

Revision ID: c039038b2d27
Revises: e0c26421e23f
Create Date: 2021-03-31 23:25:02.248792

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c039038b2d27"
down_revision = "e0c26421e23f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "pick",
        "docid",
        existing_type=sa.CHAR(length=63),
        type_=sa.String(length=63),
        existing_nullable=True,
    )
    op.alter_column(
        "pick",
        "external_docid",
        existing_type=sa.CHAR(length=63),
        type_=sa.String(length=63),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "pick",
        "external_docid",
        existing_type=sa.String(length=63),
        type_=sa.CHAR(length=63),
        existing_nullable=True,
    )
    op.alter_column(
        "pick",
        "docid",
        existing_type=sa.String(length=63),
        type_=sa.CHAR(length=63),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
