"""add beacon_id to location

Revision ID: 3fa5de011a0a
Revises: a691308d026f
Create Date: 2021-04-29 10:58:24.224826

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3fa5de011a0a"
down_revision = "a691308d026f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "location", sa.Column("beacon_id", sa.String(length=11), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("location", "beacon_id")
    # ### end Alembic commands ###
