"""add index on location in lp_moves table

Revision ID: e5ad157bef80
Revises: accd15c8ff22
Create Date: 2021-08-19 06:30:52.491236

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e5ad157bef80"
down_revision = "accd15c8ff22"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_license_plate_move_dest_location_id"),
        "license_plate_move",
        ["dest_location_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_license_plate_move_dest_location_id"), table_name="license_plate_move"
    )
    # ### end Alembic commands ###
