"""remove activity_id from shoppinglist table

Revision ID: b827407344c9
Revises: f3f46cfebdd3
Create Date: 2021-05-25 14:21:46.527077

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b827407344c9"
down_revision = "f3f46cfebdd3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "shopping_list_activity_id_fkey", "shopping_list", type_="foreignkey"
    )
    op.drop_column("shopping_list", "activity_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "shopping_list",
        sa.Column("activity_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "shopping_list_activity_id_fkey",
        "shopping_list",
        "activity",
        ["activity_id"],
        ["id"],
    )
    # ### end Alembic commands ###
