"""add external sno to lp& pick

Revision ID: 284613612228
Revises: 9b1937047211
Create Date: 2021-03-18 23:29:05.858293

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "284613612228"
down_revision = "9b1937047211"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "license_plate",
        sa.Column("external_serial_number", sa.String(length=127), nullable=True),
    )
    op.add_column(
        "license_plate", sa.Column("is_consumer_facing", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "license_plate", sa.Column("redirect_url", sa.String(length=127), nullable=True)
    )
    op.add_column("pick", sa.Column("actual_end_date", sa.DateTime(), nullable=True))
    op.add_column("pick", sa.Column("actual_start_date", sa.DateTime(), nullable=True))
    op.add_column("pick", sa.Column("docid", sa.CHAR(length=63), nullable=True))
    op.add_column("pick", sa.Column("planned_end_date", sa.DateTime(), nullable=True))
    op.add_column("pick", sa.Column("planned_start_date", sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, "pick", ["docid"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "pick", type_="unique")
    op.drop_column("pick", "planned_start_date")
    op.drop_column("pick", "planned_end_date")
    op.drop_column("pick", "docid")
    op.drop_column("pick", "actual_start_date")
    op.drop_column("pick", "actual_end_date")
    op.drop_column("license_plate", "redirect_url")
    op.drop_column("license_plate", "is_consumer_facing")
    op.drop_column("license_plate", "external_serial_number")
    # ### end Alembic commands ###
