"""add production order tables

Revision ID: e6922e7fad6a
Revises: e5ad157bef80
Create Date: 2021-10-06 23:39:38.998904

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e6922e7fad6a"
down_revision = "e5ad157bef80"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "production_order",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "location_id", sa.Integer(), nullable=True, comment="Current facility id"
        ),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("requested_qty", sa.Float(), nullable=True),
        sa.Column("planned_start_date", sa.DateTime(), nullable=True),
        sa.Column("planned_end_date", sa.DateTime(), nullable=True),
        sa.Column("actual_start_date", sa.DateTime(), nullable=True),
        sa.Column("actual_end_date", sa.DateTime(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("CREATED", "ONHOLD", "DELETED", name="productionorderstatusenum"),
            nullable=False,
        ),
        sa.Column("docid", sa.String(length=63), nullable=True),
        sa.Column("external_docid", sa.String(length=63), nullable=True),
        sa.Column("redirect_url", sa.String(length=127), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["location.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("docid"),
    )
    op.create_table(
        "production_order_lineitem",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("production_order_id", sa.Integer(), nullable=True),
        sa.Column("license_plate_id", sa.Integer(), nullable=True),
        sa.Column("license_plate_move_id", sa.Integer(), nullable=True),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column("qty", sa.Float(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "CREATED",
                "DRAFT",
                "ONHOLD",
                "COMPLETE",
                "DELETED",
                name="productionorderlineitemstatusenum",
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["license_plate_id"],
            ["license_plate.id"],
        ),
        sa.ForeignKeyConstraint(
            ["license_plate_move_id"],
            ["license_plate_move.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
        ),
        sa.ForeignKeyConstraint(
            ["production_order_id"],
            ["production_order.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("production_order_lineitem")
    op.drop_table("production_order")
    # ### end Alembic commands ###
