"""updated locations model - added unit column

Revision ID: d9ccade72896
Revises: 644c6c86bfe6
Create Date: 2022-08-19 06:12:17.314278

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "d9ccade72896"
down_revision = "644c6c86bfe6"
branch_labels = None
depends_on = None


unit_ = postgresql.ENUM("FEET", "METER", "INCHES", name="unittypeenum")


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    unit_.create(op.get_bind())

    op.add_column(
        "location",
        sa.Column("unit", unit_, nullable=True, comment="unit column data type"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("location", "unit")

    bind = op.get_bind()
    unit_.drop(bind, checkfirst=False)
    # ### end Alembic commands ###
