"""empty message

Revision ID: 319e0c93f1af
Revises: d1262191849d
Create Date: 2023-09-25 11:21:56.102466

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "319e0c93f1af"
down_revision = "d1262191849d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("location", sa.Column("logo_url", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("location", "logo_url")
    # ### end Alembic commands ###
