"""empty message

Revision ID: 6f04bd30f5ce
Revises: d9ccade72896
Create Date: 2023-01-10 19:56:59.437209

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6f04bd30f5ce"
down_revision = "d9ccade72896"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "license_plate_move", sa.Column("left_at", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("license_plate_move", "left_at")
    # ### end Alembic commands ###
