"""empty message

Revision ID: 739ccf64dd9f
Revises: 355e89fd608c
Create Date: 2024-03-18 15:48:23.451263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '739ccf64dd9f'
down_revision = '355e89fd608c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stack', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stack', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
