"""empty message

Revision ID: 2f2d2625b1d6
Revises: f56c73821f1e
Create Date: 2024-09-24 21:44:03.340169

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2f2d2625b1d6'
down_revision = '62adc1062b7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_access', sa.Boolean(), nullable=False , server_default=sa.sql.expression.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.drop_column('public_access')

    # ### end Alembic commands ###
