"""2024-08-16_added triggers column to locations table

Revision ID: f56c73821f1e
Revises: 714a350cd467
Create Date: 2024-08-16 12:17:02.561560

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f56c73821f1e'
down_revision = '714a350cd467'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trigger', postgresql.JSONB(astext_type=sa.Text()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.drop_column('trigger')

    # ### end Alembic commands ###
