"""empty message

Revision ID: 28403145818c
Revises: d573aad4e504
Create Date: 2024-05-17 17:10:37.953030

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '28403145818c'
down_revision = 'd573aad4e504'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_template', postgresql.JSONB(astext_type=sa.Text()), nullable=True))

    with op.batch_alter_table('production_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_template', postgresql.JSONB(astext_type=sa.Text()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('production_order', schema=None) as batch_op:
        batch_op.drop_column('order_template')

    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_column('order_template')

    # ### end Alembic commands ###
