"""empty message

Revision ID: 62adc1062b7d
Revises: f56c73821f1e
Create Date: 2024-09-27 20:43:21.544264

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '62adc1062b7d'
down_revision = 'f56c73821f1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lp_qty', sa.Integer(), nullable=False, server_default='0'))



    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.drop_column('lp_qty')

    # ### end Alembic commands ###
