"""empty message

Revision ID: 9bf33d0e86dd
Revises: 36699898fae1
Create Date: 2025-02-06 23:17:35.660271

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9bf33d0e86dd'
down_revision = '36699898fae1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('virtual_erp',
    sa.Column('color_code', sa.String(), nullable=True),
    sa.Column('item_id', sa.String(), nullable=True),
    sa.Column('item_num', sa.String(), nullable=True),
    sa.Column('item_sales_id', sa.String(), nullable=True),
    sa.Column('job_name', sa.String(), nullable=True),
    sa.Column('masking_batch', sa.String(length=127), nullable=True),
    sa.Column('masking_qr', sa.String(length=63), nullable=True),
    sa.Column('pur_batch', sa.String(length=127), nullable=True),
    sa.Column('pur_qr', sa.String(length=63), nullable=True),
    sa.Column('pvc_batch', sa.String(length=127), nullable=True),
    sa.Column('pvc_qr', sa.String(length=63), nullable=True),
    sa.Column('sales_order', sa.String(length=127), nullable=True),
    sa.Column('transaction_status', sa.Enum('RECEIVED', 'PAIRED', name='virtualerptransactionstatus'), nullable=True),
    sa.Column('license_plate_id', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['license_plate_id'], ['license_plate.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('virtual_erp')
    # ### end Alembic commands ###
