"""empty message

Revision ID: 1eef60e34d8a
Revises: 36699898fae1
Create Date: 2025-01-30 19:13:21.085783

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1eef60e34d8a'
down_revision = '9bf33d0e86dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_logs',
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('page', sa.String(length=256), nullable=False),
    sa.Column('stringNote', sa.String(length=63), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('user_logs')
    # ### end Alembic commands ###
