"""empty message

Revision ID: 36699898fae1
Revises: 663028a9f7f1
Create Date: 2025-01-16 20:12:39.914921

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '36699898fae1'
down_revision = '663028a9f7f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learning_video_map', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pick_type', sa.String(length=63), nullable=True))
        batch_op.add_column(sa.Column('instructions', sa.String(length=256), nullable=True))
        batch_op.drop_column('pic_type')
        batch_op.drop_column('instruction')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('learning_video_map', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instruction', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('pic_type', sa.VARCHAR(length=63), autoincrement=False, nullable=True))
        batch_op.drop_column('instructions')
        batch_op.drop_column('pick_type')

    # ### end Alembic commands ###
