"""empty message

Revision ID: 9389108c2c6c
Revises: 69defb6c55a0
Create Date: 2025-01-09 00:51:53.181682

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9389108c2c6c'
down_revision = '69defb6c55a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learning_video_map', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doc_id', sa.String(length=63), nullable=True))
        batch_op.create_unique_constraint(None, ['doc_id'])

    

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('learning_video_map', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('doc_id')

    # ### end Alembic commands ###
