"""empty message

Revision ID: 663028a9f7f1
Revises: 9389108c2c6c
Create Date: 2025-01-13 19:53:45.638219

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '663028a9f7f1'
down_revision = '9389108c2c6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learning_video_map', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pic_type', sa.String(length=63), nullable=True))
        batch_op.add_column(sa.Column('title', sa.String(length=63), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(length=63), nullable=True))
        batch_op.add_column(sa.Column('instruction', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('visibility', sa.String(length=63), nullable=True))
        batch_op.add_column(sa.Column('redirect_url', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=63), nullable=True))
        batch_op.add_column(sa.Column('thumbnail_url', sa.String(length=256), nullable=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learning_video_map', schema=None) as batch_op:
        batch_op.drop_column('thumbnail_url')
        batch_op.drop_column('email')
        batch_op.drop_column('redirect_url')
        batch_op.drop_column('visibility')
        batch_op.drop_column('instruction')
        batch_op.drop_column('description')
        batch_op.drop_column('title')
        batch_op.drop_column('pic_type')

    # ### end Alembic commands ###
