"""empty message

Revision ID: 42c3c0e9022a
Revises: 1eef60e34d8a
Create Date: 2025-02-16 00:07:18.126805

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '42c3c0e9022a'
down_revision = '1eef60e34d8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('container_move',
    sa.Column('container_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('src_location_id', sa.Integer(), nullable=True),
    sa.Column('dest_location_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=True),
    sa.Column('left_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('CREATED', 'DELETED', name='containermovestatusenum', length=31), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ),
    sa.ForeignKeyConstraint(['container_id'], ['container.id'], ),
    sa.ForeignKeyConstraint(['dest_location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['src_location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('container_move', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_container_move_container_id'), ['container_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_container_move_dest_location_id'), ['dest_location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_container_move_organization_id'), ['organization_id'], unique=False)

    with op.batch_alter_table('container', schema=None) as batch_op:
        batch_op.drop_index('ix_container_parent_container_id')
        batch_op.create_index(batch_op.f('ix_container_location_id'), ['location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_container_organization_id'), ['organization_id'], unique=False)

    with op.batch_alter_table('license_plate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('container_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_license_plate_container_id'), ['container_id'], unique=False)
        batch_op.create_foreign_key('fk_container_id', 'container', ['container_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('license_plate', schema=None) as batch_op:
        batch_op.drop_constraint('fk_container_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_license_plate_container_id'))
        batch_op.drop_column('container_id')

    with op.batch_alter_table('container', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_container_organization_id'))
        batch_op.drop_index(batch_op.f('ix_container_location_id'))
        batch_op.create_index('ix_container_parent_container_id', ['parent_container_id'], unique=False)

    with op.batch_alter_table('container_move', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_container_move_organization_id'))
        batch_op.drop_index(batch_op.f('ix_container_move_dest_location_id'))
        batch_op.drop_index(batch_op.f('ix_container_move_container_id'))

    op.drop_table('container_move')
    # ### end Alembic commands ###
