"""empty message

Revision ID: 714a350cd467
Revises: 28403145818c
Create Date: 2024-06-01 00:14:31.576457

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '714a350cd467'
down_revision = '28403145818c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute("CREATE TYPE usershiftenum AS ENUM ('NA', 'MORNING', 'DAY', 'EVENING')")
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shift', sa.Enum('NA', 'MORNING', 'DAY', 'EVENING', name='usershiftenum', length=10), nullable=True))
        
    

    # ### end Alembic commands ###


def downgrade():

    
    with op.batch_alter_table('user', schema=None) as batch_op:

        batch_op.drop_column('shift')
    op.execute('DROP TYPE usershiftenum')



    # ### end Alembic commands ###
